// <auto-generated />
using System;
using ASP.NETCoreMVCAPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETCoreMVCAPP.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20230224215835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.HasKey("CourseId")
                        .HasName("PK_COURSE_ID");

                    b.HasIndex(new[] { "Name" }, "UQ_COURSE_NAME")
                        .IsUnique();

                    b.ToTable("COURSES");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.HasKey("GroupId")
                        .HasName("PK_GROUP_ID");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "Name" }, "UQ_GROUP_NAME")
                        .IsUnique();

                    b.ToTable("GROUPS");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("StudentId")
                        .HasName("PK_STUDENT_ID");

                    b.HasIndex("GroupId");

                    b.ToTable("STUDENTS");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Group", b =>
                {
                    b.HasOne("ASP.NETCoreMVCAPP.Models.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_GROUPS_To_COURSES");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Student", b =>
                {
                    b.HasOne("ASP.NETCoreMVCAPP.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_STUDENTS_To_GROUPS");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("ASP.NETCoreMVCAPP.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
